{% set name = "quacc" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quacc-{{ version }}.tar.gz
  sha256: ad2319e1d93ef3fa5f0a9bcc7da3ba83a12896c94fbd12a927e7e7f68d0de74d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
  run:
    - ase >=3.22.1
    - cclib =1.8
    - custodian =2023.7.22
    - emmet-core =0.66.0
    - maggma =0.53.1
    - monty >=2023.9.5
    - numpy =1.25.2
    - pydantic =1.10.2
    - pymatgen >=2023.9.2
    - python >=3.10
    - typer

test:
  imports:
    - quacc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/arosen93/quacc
  summary: Enhance ASE for high-throughput DFT
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
