{% set name = "quacc" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quacc-{{ version }}.tar.gz
  sha256: 11d0c7cf031d23fe482af990af6a4b51c533080309affa112079be9ece9d2aae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
  run:
    - ase >=3.22.1
    - cclib =1.8
    - custodian =2023.7.22
    - emmet-core =0.66.0
    - maggma =0.53.1
    - monty =2023.8.8
    - numpy =1.25.2
    - pydantic =1.10.2
    - pymatgen =2023.8.10
    - python >=3.10

test:
  imports:
    - quacc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/arosen93/quacc
  summary: Enhance ASE for high-throughput DFT
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
