{% set name = "quacc" %}
{% set version = "1.0.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quacc-{{ version }}.tar.gz
  sha256: 979ab0c53370bab6bf8f8287a844923340069b429703023f35bfe5ece46131b5

build:
  entry_points:
    - quacc = quacc._cli.quacc:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - ase >=3.23.0
    - custodian >=2025.5.12
    - emmet-core >=0.84.6
    - maggma >=0.64.0
    - monty >=2024.5.15
    - numpy >=1.25.0
    - psutil
    - pydantic >=2.0.1
    - pydantic-settings >=2.2.0
    - pymatgen >=2024.10.22
    - ruamel.yaml >=0.17.40
    - typer >=0.12.1
    - pymongo <=4.10.1
    - frozendict
    - click <8.2

test:
  imports:
    - quacc
  commands:
    - pip check
    - quacc --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Quantum-Accelerators/quacc
  summary: A platform to enable high-throughput, database-driven quantum chemistry and computational materials science
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
