{% set name = "quacc" %}
{% set version = "0.11.9" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quacc-{{ version }}.tar.gz
  sha256: 701aa9b5d43502e3849e218c5e1792ff0c2c16ae96512c87c94a888e26dead2e

build:
  entry_points:
    - quacc = quacc._cli.quacc:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - ase >=3.23.0
    - custodian >=2024.3.12
    - emmet-core >=0.84.3rc6
    - maggma >=0.64.0
    - monty >=2024.5.15
    - numpy >=1.25.0
    - psutil
    - pydantic >=2.0.1
    - pydantic-settings >=2.2.0
    - pymatgen >=2024.10.22
    - ruamel.yaml >=0.17.40
    - typer >=0.12.1

test:
  imports:
    - quacc
  commands:
    - pip check
    - quacc --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Quantum-Accelerators/quacc
  summary: A platform to enable high-throughput, database-driven quantum chemistry and computational materials science
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
