schema_version: 1

context:
  name: quacc
  version: 1.2.6
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/quacc-${{ version }}.tar.gz
  sha256: d93d97f6a6c425675e7b3185b477890d5b7bea84a07b3d7277bb63d037e666b5

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - quacc = quacc._cli.quacc:app

requirements:
  host:
    - python 3.11.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - ase >=3.23.0
    - custodian >=2025.12.14
    - emmet-core >=0.84.6
    - maggma >=0.64.0
    - monty >=2024.5.15
    - numpy >=1.25.0
    - psutil
    - pydantic >=2.0.1
    - pydantic-settings >=2.2.0
    - pymatgen >=2024.10.22
    - ruamel.yaml >=0.17.40
    - typer >=0.12.1
    - pymongo <=4.10.1
    - frozendict
    - click <8.2

tests:
  - python:
      imports:
        - quacc
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - quacc --help

about:
  summary: A platform to enable high-throughput, database-driven quantum chemistry and computational materials science
  license: BSD-3-Clause
  license_file: LICENSE.md
  homepage: https://github.com/Quantum-Accelerators/quacc

extra:
  recipe-maintainers:
    - jan-janssen
